{
  final Callable<?> closure=(Callable<?>)arg;
  Object retval=null;
  try {
    retval=closure.call();
  }
 catch (  final Exception e) {
    logger.log(Level.SEVERE,"A closure entry failed to execute: " + e,e);
    throw new USMException("Launch of process from closure exited with an exception: " + e.getMessage(),e);
  }
  if (retval == null) {
    return null;
  }
  if (retval instanceof Process) {
    return (Process)retval;
  }
  logger.warning("The Start closure returned a non-null value that is not a Process. " + "This value will be ignored! Returned value was of type: " + retval.getClass().getName() + ". Value was: "+ retval);
  return null;
}
